FROM python:3.8
LABEL maintainer="Nicklas Faerch"

COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt

EXPOSE 3111

# command to run on container start
CMD ["sh", "-c", "python init_db.py && python app.py"]
